name: Build Android APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - uses: android-actions/setup-android@v3
      
      - name: install dependencies
        run: cd android; ./gradlew dependencies
      
      - name: build
        run: cd android; ./gradlew assembleRelease
      
      - name: upload apk
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
