name: Build
on:
  push:
    branches:
      - master

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: install dependencies
        run: cd executable; npm install
      - name: build
        run: cd executable; npm run make

  # build_on_mac:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@master
  #       with:
  #         node-version: 14
  #     - name: move to folder
  #       run: cd executable
  #     - name: install dependencies
  #       run: npm install
  #     - name: build
  #       run: npm run make

  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: install dependencies
        run: cd executable; npm install
      - name: build
        run: cd executable; npm run make
